name = "infst"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
JWT_SECRET = "change-me-in-production"

[[d1_databases]]
binding = "DB"
database_name = "infst-db"
migrations_dir = "drizzle"
